compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  //npm.siteed.net:
    npmAlwaysAuth: true
    npmAuthToken: "${SITEED_NPM_TOKEN}"
  "https://registry.npmjs.org":
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN}"
