#!/bin/bash
# iOS Integration Test Information for sherpa-onnx.rn

echo "📱 iOS Integration Testing for sherpa-onnx.rn"
echo "============================================="
echo ""
echo "⚠️  IMPORTANT: iOS does not support true integration tests like Android"
echo ""
echo "Why iOS integration tests are different:"
echo "• Android: Can run instrumented tests that directly call native modules"
echo "• iOS: Unit tests cannot access React Native modules without the full app running"
echo ""
echo "How to test sherpa-onnx.rn on iOS:"
echo ""
echo "1. Manual Testing (Recommended):"
echo "   cd ../../apps/sherpa-onnx-demo"
echo "   yarn ios"
echo "   # Test getSystemInfo and getArchitectureInfo in the app"
echo ""
echo "2. E2E Testing with Detox (Automated):"
echo "   # Install Detox and write tests that interact with the running app"
echo "   # See: https://wix.github.io/Detox/"
echo ""
echo "3. Unit Tests (Limited):"
echo "   # Can only test isolated native code, not React Native module integration"
echo "   # Must be set up in Xcode for each prebuild"
echo ""
echo "Unlike Android, iOS requires the full React Native app to be running"
echo "to test native modules. This is a platform limitation, not a bug."