#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PKG_DIR="$(dirname "$SCRIPT_DIR")"
CPP_DIR="$PKG_DIR/cpp"
OUT_DIR="$PKG_DIR/prebuilt/wasm"
TMP_DIR="$(mktemp -d)"

mkdir -p "$OUT_DIR"

echo "Building mel-spectrogram WASM module (with audio features)..."

# Compile C files separately (no -std=c++17)
emcc -O2 -I"$CPP_DIR/kiss_fft" -c "$CPP_DIR/kiss_fft/kiss_fft.c" -o "$TMP_DIR/kiss_fft.o"
emcc -O2 -I"$CPP_DIR/kiss_fft" -c "$CPP_DIR/kiss_fft/kiss_fftr.c" -o "$TMP_DIR/kiss_fftr.o"

# Compile C++ files
emcc -O2 -std=c++17 -I"$CPP_DIR" -I"$CPP_DIR/kiss_fft" -c "$CPP_DIR/MelSpectrogram.cpp" -o "$TMP_DIR/MelSpectrogram.o"
emcc -O2 -std=c++17 -I"$CPP_DIR" -I"$CPP_DIR/kiss_fft" -c "$CPP_DIR/MelSpectrogramBridge.cpp" -o "$TMP_DIR/MelSpectrogramBridge.o"
emcc -O2 -std=c++17 -I"$CPP_DIR" -I"$CPP_DIR/kiss_fft" -c "$CPP_DIR/AudioFeatures.cpp" -o "$TMP_DIR/AudioFeatures.o"
emcc -O2 -std=c++17 -I"$CPP_DIR" -I"$CPP_DIR/kiss_fft" -c "$CPP_DIR/AudioFeaturesBridge.cpp" -o "$TMP_DIR/AudioFeaturesBridge.o"

# Link
emcc \
  "$TMP_DIR/kiss_fft.o" \
  "$TMP_DIR/kiss_fftr.o" \
  "$TMP_DIR/MelSpectrogram.o" \
  "$TMP_DIR/MelSpectrogramBridge.o" \
  "$TMP_DIR/AudioFeatures.o" \
  "$TMP_DIR/AudioFeaturesBridge.o" \
  -O2 \
  -s MODULARIZE=1 \
  -s EXPORT_NAME="createMelSpectrogramModule" \
  -s EXPORTED_FUNCTIONS='["_mel_spectrogram_compute","_mel_spectrogram_free","_mel_spectrogram_init","_mel_spectrogram_compute_frame","_mel_spectrogram_get_n_mels","_audio_features_compute","_audio_features_free","_audio_features_init","_audio_features_compute_frame","_audio_features_free_arrays","_audio_features_get_n_mfcc","_malloc","_free"]' \
  -s EXPORTED_RUNTIME_METHODS='["ccall","cwrap","getValue"]' \
  -s SINGLE_FILE=1 \
  -s ALLOW_MEMORY_GROWTH=1 \
  -s ENVIRONMENT='web,worker' \
  -o "$OUT_DIR/mel-spectrogram.js"

rm -rf "$TMP_DIR"

echo "Built: $OUT_DIR/mel-spectrogram.js ($(wc -c < "$OUT_DIR/mel-spectrogram.js" | tr -d ' ') bytes)"

# Generate a TS module that exports the WASM glue as a string constant.
# This is used by the web worker to load WASM inside the worker context.
GLUE_TS="$PKG_DIR/src/workers/wasmGlueString.web.ts"
echo "Generating $GLUE_TS ..."

{
  echo '// AUTO-GENERATED by build-wasm.sh — do not edit manually.'
  echo '// Contains the Emscripten WASM glue JS (with embedded base64 wasm binary)'
  echo '// for loading inside web workers.'
  echo '/* eslint-disable */'
  echo -n 'export const wasmGlueJs: string = `'
  # Escape backticks and ${} in the JS source so they survive the template literal
  sed -e 's/`/\\`/g' -e 's/\$\({[^}]*}\)/\\$\1/g' "$OUT_DIR/mel-spectrogram.js"
  echo '`;'
} > "$GLUE_TS"

echo "Generated: $GLUE_TS ($(wc -c < "$GLUE_TS" | tr -d ' ') bytes)"
