name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been marked as stale due to 3 weeks of inactivity. It will be closed in 3 days if no further activity occurs.'
          close-issue-message: 'This issue has been automatically closed due to inactivity. Please feel free to reopen if this is still relevant.'
          days-before-issue-stale: 21  # Mark issues as stale after 21 days (3 weeks)
          days-before-issue-close: 3   # Close stale issues after 3 more days
          exempt-issue-labels: 'pinned,security,bug,enhancement'  # Issues with these labels won't be marked as stale
          stale-issue-label: 'stale'   # Label to apply to stale issues
          days-before-pr-stale: -1     # Disable for PRs (-1 means never mark PRs as stale)
          days-before-pr-close: -1     # Disable for PRs (-1 means never close PRs) 